# Generated by Django 2.1.3 on 2018-12-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181217_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '产品信息'},
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=20, verbose_name='商品高度'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名字'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Type', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='商品宽度'),
        ),
    ]
